### ISSUE TITLE
Maintenance.md might not omit all marrach specific portbase

### ISSUE THREAD

**Issue by shentino** [ChatTheatre/SkotOS#10]
The latest commit to Maintenance.md specifies 8000 in some places, I suspect this might need to be converted to X000

**Comment by shannona** [comment]
If you're talking about the diagram, the 80XXs are correct. 8080 is the alternate HTML port to 80, which is where nginx is installed. Nginx related ports then count up from there for consistency.

(Marrach was actually a problem because it was also at 80XX and shouldn't have been.)

**Comment by shannona** [comment]
And if there is anything in the doc text not related to nginx and its related-ports, feel free to PR it.

**Comment by shentino** [comment]
> If you're talking about the diagram, the 80XXs are correct. 8080 is the alternate HTML port to 80, which is where nginx is installed. Nginx related ports then count up from there for consistency.
> 
> (Marrach was actually a problem because it was also at 80XX and shouldn't have been.)

Ironically Marrach being assigned 8XXX is exactly why I thought this was a mistake in the first place as it smelled like a marrach specific number
