### ISSUE TITLE
Document StoryGuides in Learning-the-Ropes.md

### ISSUE THREAD

**Issue by shentino** [ChatTheatre/SkotOS#13]
self explanatory but I noticed that they were left out of the document.

**Comment by ChristopherA** [comment]
It turns out Marrach has turned all of those commands off. All their guides are now staff. None of the other games used them very well either. It may be difference of scale.

**Comment by shentino** [comment]
true enough but my comment was more directed towards documentation of the intended/traditional duties of the role in question

**Comment by shannona** [comment]
Yeah, feel free to PR 8000 to X000 if you'd like.

**Comment by shentino** [comment]
Like for example, what a StoryGuide actually does, and has nothing to do with ! commands

**Comment by noahgibbs** [comment]
These days we're doing this in SkotOS-Doc. There's a fair bit of it in place and more coming.
