### ISSUE TITLE
Can't seem to commit XML changes to WOE:System:Developers

### ISSUE THREAD

**Issue by ChristopherA** [ChatTheatre/SkotOS#14]
If you edit out all the old users in WOE:System:Developers using the XML edit mode, none of the changes get committed. You have to delete them by hand from the [V] interface.

**Comment by noahgibbs** [comment]
One oddity that may be relevant here: if you log in (in most ways), SkotOS will automatically add or remove you to System:Developers as appropriate. So if you try to edit *yourself* (or anybody else who logs in or out around the time you're editing,) it's going to give some funky behaviour.

**Comment by noahgibbs** [comment]
At this point there's no longer a reason to update WOE:System:Developers manually. It should be updated automatically. If it isn't in some case file a bug and I'll fix that.
