### ISSUE TITLE
Error in mac_setup.sh, no skotos_dev_ngnix.conf

### ISSUE THREAD

**Issue by ChristopherA** [ChatTheatre/SkotOS#23]
Fresh clone https://github.com/ChatTheatre/SkotOS/commit/1391657ad38784e476a412752c7b9466e641dde4 of SkotOS in my local ChatTheatre dev directory, based on today's #22.

Did a `cd SkotOS` then `./dev_scripts/mac_setup.sh`

Got this error:

```
./dev_scripts/mac_setup.sh: line 115: /usr/local/etc/nginx/servers/skotos_dev_nginx.conf: No such file or directory
```

**Comment by noahgibbs** [comment]
Oh, interesting. Do you know if you have an NGinX *not* installed via Homebrew by any chance?

**Comment by noahgibbs** [comment]
Relatedly: may I ask you to run this command? `nginx -V 2>&1 | grep -o '\-\-conf-path=\(.*conf\)' | cut -d '=' -f2`

On my Mac I'm getting /usr/local/etc/nginx/nginx.conf, but I suspect you'll get something different.

**Comment by ChristopherA** [comment]
I'm getting the same path:

```
% nginx -V 2>&1 | grep -o '\-\-conf-path=\(.*conf\)' | cut -d '=' -f2
/usr/local/etc/nginx/nginx.conf
```

**Comment by ChristopherA** [comment]
I was following the instructions from the README.md, which didn't mention I needed to separately `brew install nginx`. As there is no harm for the script to do so, I assumed it handled those kinds of dependencies.

**Comment by ChristopherA** [comment]
Though looking now, I see

```
% brew install nginx
Warning: nginx 1.19.3 is already installed and up-to-date
To reinstall 1.19.3, run `brew reinstall nginx`
```

**Comment by noahgibbs** [comment]
The script will "brew install nginx" if there's no nginx in the path. So you have it, but I guess it's not in your path? The file not found error is also odd - I *think* that's saying you don't have a directory /usr/local/etc/nginx/servers/.

I'm on minor version behind you, so I'm updating in case it's something they just changed.

**Comment by noahgibbs** [comment]
Huh. Look at that. They made a big incompatible change between 1.19.2 and 1.19.3. Not standard versioning!

```
==> Caveats
Docroot is: /usr/local/var/www

The default port has been set in /usr/local/etc/nginx/nginx.conf to 8080 so that
nginx can run without sudo.

nginx will load all files in /usr/local/etc/nginx/servers/.
```

But they probably don't *create* that directory, they just check it if it exists. Argh. I'll fix that.

**Comment by noahgibbs** [comment]
Attempted fix for this with https://github.com/ChatTheatre/SkotOS/pull/25

**Comment by noahgibbs** [comment]
Chris, did this fix the problem you were seeing?

**Comment by noahgibbs** [comment]
I believe this problem should be gone for awhile now.
