### ISSUE TITLE
Scheduling Orchil update to former Skotos games

### ISSUE THREAD

**Issue by ChristopherA** [ChatTheatre/SkotOS#24]
There is a new version of the Orchil client which has fixes to one important bug, and some minor features.

@shentino can you talk with the leads about scheduling this update?

**Comment by shentino** [comment]
Huh?

Is there anything more to this than me just arranging to have them upload it to their machines?

I've never worked much with the internals of Orchil.  My domain has mostly been VM work on the hosting servers and low level LPC code in Skotoslib.

Are you just wanting me to have them pull it?

**Comment by noahgibbs** [comment]
I think Community makes more sense for this. It's not really a core-SkotOS bug.
