### ISSUE TITLE
missing filewoe documentation

### ISSUE THREAD

**Issue by shentino** [ChatTheatre/SkotOS#3]
Something possibly on port X090..the ability to upload and download files with the server as a developer?

I found a java class file to handle this as an applet but no java source was found.

**Comment by noahgibbs** [comment]
What I'm seeing on port X090 looks like it's mostly sending HTML snippets which have URLs on the main HTTP port. That's also why it has basically no security - it uses the main HTTP port, which *does* have security and prevent non-wizards from seeing specifics they shouldn't. So it's mostly just serving the equivalent of Orchil, but for parts of the Tree of WOE.

So if you downloaded interesting files, you'd be downloading them off the main HTTP port, not X090. I also see skoot/usr/DevSys/obj/filewoe.c, which looks like the server side of FileWoe on port X091. Like port X090, it serves SAM links that are from the main HTTP port.

So what's in that Java source is almost guaranteed to be a socket client that downloads the list of URLs, then uses an HTTP client that sends cookies for SkotOS login, then downloads files. A lot of files. To a first approximation, all the files.

Specifically: filewoe.c is going through everything under the DGD root and sending download URLs (/Dev/File.sam with the appropriate filename) for everything the user has READ access to at the kernellib level. It's using call_out to slow it down, but it's just sending everything the user can read.

My assumption is that it's meant for backup. The only way it can be choosy is if you carefully set the kernellib-level access to not let it read everything. It's gonna send whatever it can see.

**Comment by noahgibbs** [comment]
What's even weirder is that I don't see it using AuthAPI. So I don't think it will send the list of files *that user* can see. I think X091 is an unauthenticated port that just sends everything, but only somebody with appropriate access on port X080 can download that file, even though anybody can see its name.

On the plus side, I'm pretty sure it's unused now. Looks like exportd has the same port number and replaced it.

ExportD looks like it was intended to be a real replacement but... didn't happen. Instead it creates a login. If you telnet to that port now, you get a login prompt, no password prompt, but there don't seem to be any valid commands. So it's empty but harmless. There's nothing in the code that would export any objects.

**Comment by noahgibbs** [comment]
I'll add port 90 to the DEPRECATIONS file with some comments. Definitely no need to document it at this point - the current implementation is a no-op.
