### ISSUE TITLE
mac_setup.sh fails to open log window when using Apple_Terminal

### ISSUE THREAD

**Issue by saraht45** [ChatTheatre/SkotOS#59]
When executing the command, everything works fine but I get this message:

+ open -a Apple_Terminal -n deploy_scripts/mac_setup/show_dgd_logs.sh
+ dgd/bin/dgd ./skotos.dgd skotos.database
Unable to find application named 'Apple_Terminal'

I assume this is just because I don't have an application named "Apple_terminal" and may not be an issue but I thought it worth mentioning.

**Comment by ChristopherA** [comment]
On my computer, the app is named just "Terminal". May @noahgibbs renamed it?

**Comment by saraht45** [comment]
It looks like the code is referencing an environment variable called $TERM_PROGRAM

`open -a $TERM_PROGRAM -n deploy_scripts/mac_setup/show_dgd_logs.sh`

When I use the "env" command in the terminal, it gives me an output with this line:

`TERM_PROGRAM=Apple_Terminal`

Manually inputting the command 'open -a Apple_Terminal' gives the same error but 'open -a Terminal' is successful.

**Comment by noahgibbs** [comment]
Hm. I tested this on my computer's iTerm2 and Apple Terminal programs. But apparently I should go back to the old way or do some kind of mapping...

**Comment by noahgibbs** [comment]
This should be fixed by https://github.com/ChatTheatre/SkotOS/pull/63 when it gets merged.

(I've also made it much easier to use a different SkotOS branch to get a SkotOS fix from gables_game or vRWOT, and I'll document how very soon.)
