### ISSUE TITLE
Missing GAME_ROOT reference show_dgd_logs.sh

### ISSUE THREAD

**Issue by saraht45** [ChatTheatre/SkotOS#60]
Attempting to run this script from the command line gives me an error:

You must set a GAME_ROOT to run this setup script.

This script gets called from the start_server.sh script but would be nice to have the option to call it manually if needed.

**Comment by noahgibbs** [comment]
Ah, hey, I should have talked to you about this. You know the whole "SkotOS is the library, separate from the game" thing? I've been doing more of that, and there will only be more in the future.

So: try cloning https://github.com/ChatTheatre/gables_game and running the local setup script. That should give you a functional SkotOS game. It's possible to do this all with "just" SkotOS by setting GAME_ROOT, but the plan is for it to become impossible in the future.

(If you run the script from gables_game it should set GAME_ROOT for you automatically.)

**Comment by saraht45** [comment]
Gotcha. I do remember reading that in the VPS setup guide. I'll give that a shot. Will this still allow me to make changes on my machine and submit those changes back to SkotOS (as I'm updating links as we previously discussed)?

**Comment by noahgibbs** [comment]
Oh, hey, that will complicate that a bit ("yes, but...").

So: the way the new game-and-library architecture works is that the game assembles a directory called ".root" under its own directory. That directory is the SkotOS library, with the games own override files copied over. So: in the finished, running game the ".root" directory works like you're used to "skoot" working.

If you make changes to file under .root, that will be great for testing them. You can then copy the finished files, when they work, into the SkotOS repo under "skoot" and make a pull request. There are several other ways you can do it - let me know if this one isn't your favourite.

**Comment by noahgibbs** [comment]
Sounds like this is working better now that you're using gables_game. I'll close this.
