### ISSUE TITLE
Tool:Lib:Popup missing after cold boot

### ISSUE THREAD

**Issue by saraht45** [ChatTheatre/SkotOS#61]
When doing a local cold boot of SkotOS, Tool:Lib:Popup is missing which causes other issues in Tree of Woe. Trying to load any file results in:

`cannot resolve ${Tool:Lib:Popup}`

Tool:Lib:Popup does appear in /skoot/data/vault. I have also tried cold booting my Lovecraft Country vault dump and Tool:Lib:Popup is still missing. The dgd log shows this error during the boot process:

`May  1 19:22:30 ** Could not load Tool:Lib:Popup, not found`

**Comment by saraht45** [comment]
It may also be worth noting that this happens when attempting a local install on Mac. I will be attempting a server install soon.

**Comment by noahgibbs** [comment]
Let me know if this still happens with the gables_game method we talked about. It shouldn't. So if you still see it, that's a bug and I should track it down. This isn't one I've seen before.

**Comment by noahgibbs** [comment]
Was this fixed for you by using gables_game? Or are you still seeing it?

**Comment by saraht45** [comment]
This was fixed with the gables_game install.
