### ISSUE TITLE
Ports fail to open when running local Gables instance

### ISSUE THREAD

**Issue by saraht45** [ChatTheatre/SkotOS#65]
Running the Gables mac setup seems to happen successfully. However, manually running the show_dgd_logs.sh script shows an error and it's hard to know if dgd actually booted successfully.

$ ./show_dgd_logs.sh
tail: /log/dgd_server.out: No such file or directory
tail: /log/wafer_log.txt: No such file or directory

Wafer does not load and cannot be loaded manually.

$ wafer
Got exception in thread! Dying! Connection refused - connect(2) for "127.0.0.1" port 10070

When attempting to load dgd manually, the output reveals that several ports failed to open. Rebooting my computer does not help.

May  3 22:00:44 ** info:DEV_USERD: accepting connections on telnet devport 10098
May  3 22:00:44 ** critical:Panic: failed to open binary devport 10099
May  3 22:00:44 ** critical:Panic: failed to open Broadcast TCP port 10017
May  3 22:00:44 ** critical:Panic: failed to open AUTHD TCP port 10070
May  3 22:00:44 ** critical:Panic: failed to open CTLD TCP port 10071
May  3 22:00:44 ** critical:Panic: failed to open HTTP port: 10080
May  3 22:00:44 ** critical:Panic: failed to open HTTP port: 10089
May  3 22:00:44 ** critical:Panic: failed to open Woe port 10090
May  3 22:00:44 ** info:WOED: opened port 10090 successfully.
May  3 22:00:44 ** info:TextIF: accepting connections on game port 10443

Not sure if this is an issue on my end but I did not have the same port trouble when loading dgd from the SkotOS repo.

**Comment by noahgibbs** [comment]
The show_dgd_logs error should be resolved by the terminal patch you're reviewing. It's an error -- you're not seeing the logs -- but it's one I have a fix for.

The second one is more surprising. It means DGD can't open its ports. I mostly try to check if DGD is running before I run it again, but this *is* what you would see if a copy of DGD were already running. Maybe check that?

Certainly if you were to start the DGD server from SkotOS and then try from gables_game you'd get something like this.

**Comment by noahgibbs** [comment]
Also, if you have any trouble with show_dgd_logs in the future - it's just running "tail -f" on a couple of logfiles. "Tail -f" just shows the end of the file and then hangs around printing out anything new to the console as it arrives. The only hard part is figuring out exactly where to run it from -- so of course that's what I'm screwing up ;-) But it's a one-liner if you just want to do the same thing for yourself.

**Comment by saraht45** [comment]
Thanks for the "tail -f" tip. That helps!

The port issue seems to have resolved so it sounds like I probably had dgd running from the other setup. Since the log issue is a known issue, this can probably be closed.
