### ISSUE TITLE
Reaudit object XML dump

### ISSUE THREAD

**Issue by shentino** [ChatTheatre/SkotOS#9]
Some state was missing in the old SID that didn't get dumped, which would make it harder to both preserve enough information for a cold boot as well as hampering runtime manipulation through the WOE interface.

Example: Whether doors are closed in addition to being locked.

**Comment by shentino** [comment]
I also want to have a top down list of all the files we're redacting and why.

* Personal information/confidentiality issues
* Copyright/legal issues, example ironclaw or lovecraft related

**Comment by noahgibbs** [comment]
At this point we're saving a pretty good amount in the cold-boot dumps in terms of "blueprint" information -- great for spinning up a new instance. We're not saving spawns or some short-term state except in the statedump, and for now I think that's fine.
